{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "E-commerce API",
    "description" : "A REST API for an e-commerce service",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://virtserver.swaggerhub.com/DominykMcNamara/eCommerceAPI/1.0.0",
    "description" : "SwaggerHub API Auto Mocking"
  } ],
  "paths" : { },
  "components" : { }
}